name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Decode api.properties
        env:
          API_SECRET: ${{ secrets.API_SECRET }}
        run: echo $API_SECRET > ./api.properties

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build --info

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk  
          path: app/build/outputs/apk/debug/app-debug.apk

